#define MONO_IZQUIERDA "./mono izquierda &"
#define MONO_DERECHA "./mono derecha &"
#define X_PUNTO_INICIAL_IZQUIERDA	230 
#define Y_PUNTO_INICIAL_IZQUIERDA	280
#define X_PUNTO_INICIAL_DERECHA	500
#define Y_PUNTO_INICIAL_DERECHA	280
